spring:
  application:
    name: auth-service
  datasource:
    username: security
    password: postgres
    url: jdbc:postgresql://localhost:5432/airline-security
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
  issuer: ${spring.application.name}
  expires-in: 240
  refresh:
    expires-in: 2592000